'use strict'

const events = {

  /*
   * WINDOW
   */

  WINDOW_RESIZE: 'WINDOW_RESIZE',

  /*
   * ROUTER
   */

  ROUTER_ROUTE_CHANGE: 'ROUTER_ROUTE_CHANGE',

  CSV_ERROR: 'CSV_ERROR',

  CSV_LOADED: 'DEALS_LOADED',
  ASSETS_LOADED: 'ASSETS_LOADED',
  BEGIN_LOADING: 'BEGIN_LOADING',
  END_LOADING: 'END_LOADING',

  SECTION_INTRO: 'SECTION_INTRO',

  SECTION_LINK: 'SECTION_LINK',
  NEXT_LINK: 'NEXT_LINK',
  PREV_LINK: 'PREV_LINK',

  SECTION_ABOUT: 'SECTION_ABOUT',

  NEXT_TAG: 'NEXT_TAG',
  PREV_TAG: 'PREV_TAG',
  SECTION_TAG: 'SECTION_TAG',
  SECTION_SUBMIT_A_LINK: 'SECTION_SUBMIT_A_LINK',
  SHOW_SHARE_POP: 'SHOW_SHARE_POP'

}

module.exports = events
